### ISSUE TITLE
plugin doesn't show on Extensions menu

### ISSUE THREAD

**Issue by sakoula** [fieldOfView/Cura-SettingVisibilityProfileCreator#1]
Hi,

I am using 10.14.6 (macos mojave) and cura 4.0.0. I have installed the plugin from the marketplace and from github but the menu does not appears on the Extension menu

The plugin is installed in `~/Library/Application Support/cura/4.0/plugins/SettingVisibilityProfileCreator/SettingVisibilityProfileCreator`

Is this a known issue? 

Thanks for the great plugin! Once it will work this will be the ultimate plugin!!!

**Comment by fieldOfView** [comment]
Can you share a logfile? Go to Help -> Show configuration folder. Then locate cura.log and post it somewhere so I can download it and have a look

**Comment by SmithyAT** [comment]
Same issue here, MacOS 10.14.6 and the latest plugin version installed via Cura Marketplace. The menu item is not shown.

<img width="188" alt="Bildschirmfoto 2019-09-10 um 15 11 05" src="https://user-images.githubusercontent.com/30844629/64616635-3e6bdc00-d3dd-11e9-9cab-558d54772ca0.png">

Additional info, the Settings Guide plugin from ghostkeeper is also not shown in the menu. Others are working.

Here the Cura Log after starting:
[cura.log](https://github.com/fieldOfView/Cura-SettingVisibilityProfileCreator/files/3595769/cura.log)

**Comment by SmithyAT** [comment]
The think the problem is this line:
#self.setMenuName(catalog.i18nc("@item:inmenu", "Setting Visibility Sets"))

After commenting out, it works for me.

**Comment by fieldOfView** [comment]
Thanks for debugging
Instead of commenting out the line, could you try editing the string "Setting Visibility Sets"? Eg removing the word "Setting", or putting something in front of the word "Setting"?

**Comment by SmithyAT** [comment]
You are right, if the string starts with "Settings" then it is not shown. I tried a lot of combinations and thought maybe it is the length of the string, but it is not.

Have now "Save Setting Visibility Sets" and it works. 

I guess this also explains why ghostkeepers Settings Guide is not shown.

**Comment by fieldOfView** [comment]
Everything that starts with "Setting" or "Settings"? Could you try "Setting-visibility"?

**Comment by SmithyAT** [comment]
No, not working. I tried Setting-visibility, Setting_visibility.
Then tried _Setting-visibility and Seting-visibility (with only one t) and both are working.

**Comment by SmithyAT** [comment]
It is also not case sensitive, so setting-visibility is also not working.

**Comment by fieldOfView** [comment]
Thanks, I'll change the menu title to "Custom Setting Visibility Sets"

**Comment by SmithyAT** [comment]
Any idea why this is a problem only on Mac? I guess the string will be parsed by a library, but then it should also happen on Windows, or not?

**Comment by fieldOfView** [comment]
I think this has to do with the OSX user guidelines, which specify that a "Preferences" menu-item has to go into the application menu ("Cura", to the left of the "File" menu). Qt or OSX actually moves menu-items there. Perhaps it is doing something similar with menus starting with the word "Setting" :-/

**Comment by fieldOfView** [comment]
Fixed here: 0d41f8af7ba97d7a9c1d518a0a6f05226618a187

**Comment by meteozond** [comment]
Oh carp, how much time I've spent trying to find the problem! Thanks!

**Comment by sakoula** [comment]
Thanks for fixing this!!!!

I saw that it saves a .cfg file in the `4.0/setting_visibility` directory. This is amazing!!! Can I restore somehow the settings on the menu? Is it ok if I edit `cura.cfg` and update the `general > visible_settings` variable?

Thanks again!!!

**Comment by fieldOfView** [comment]
>  Can I restore somehow the settings on the menu?

I am not quite sure what you are asking. When you use the "Store Custom Setting Visibility Set" menu, the set should be added to the menu to the right of the "Search..." field on top of the Custom settings:
![image](https://user-images.githubusercontent.com/143551/64944240-36dd8480-d86e-11e9-9389-bb07d5e9f70b.png)

**Comment by SmithyAT** [comment]
I think the question was related to how to "transport" the set to another installation of Cura. But I guess just coping the set file should work, or not?

**Comment by fieldOfView** [comment]
> just coping the set file should work

Correct

**Comment by sakoula** [comment]
Sorry! I have not seen the `Manage Setting Visibility` menu. I thought that the only menu available was the `Extensions > Custom Settings Visibility Sets > Store Custom Setting Visibility Set` . 

Perhaps this screenshot is useful for the main readme.

Also I just upgraded from `4.0` to `4.2.1` on macOS and all the 4.0 directory was copied to 4.2 and the plugin is working without any other action and found the settings configuration.

Thanks for the great plugin!

**Comment by fieldOfView** [comment]
`Extensions > Custom Settings Visibility Sets > Store Custom Setting Visibility Set` is the only menu provided by this plugin. The rest is standard Cura functionality.

**Comment by sakoula** [comment]
Sorry for my previous posts. I just realised after your post how the plugin work. Great work! Thanks
