### ISSUE TITLE
Menu item not visible (OSX)

### ISSUE THREAD

**Issue by SmithyAT** [fieldOfView/Cura-SettingVisibilityProfileCreator#5]
The menu item "Setting Visibility Sets" is not visible. When I rename it to i.e. "My Setting Visibility Sets" then it is working. We had this issue in the past, but I am not sure if it was fixed in the meantime or not. We found out that Cura don't like a menu item name which begins with "Setting....". 

Ghostkeepers "Settings Guide" is working, so there must be something different in his plugin, that the menu item name which also begins with "Setting" is not affected.

**Comment by fieldOfView** [comment]
https://github.com/fieldOfView/Cura-SettingVisibilityProfileCreator/issues/1 seems to be rearing its ugly head again.

**Comment by vogler** [comment]
Same here.
Works after changing the string to `Custom Setting Visibility Sets`: https://github.com/fieldOfView/Cura-SettingVisibilityProfileCreator/blob/b7d71af58c4063d0b296013a640b99394d64cb1c/SettingVisibilityProfileCreator.py#L42

**Comment by fieldOfView** [comment]
This has been fixed in the master branch, but I have not come around to publishing a new version to the Marketplace. Until I do, I'll leave this issue open.
